version: "3"

services:
  app:
    image: kennylajara/job-skills-analyzer
    volumes:
      - .:/code
    ports:
      - "3000:80"

networks:
  default:
    name: nginxproxymanager_default
    external: true
