version: "3"

services:
  app:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "3000:80"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

networks:
  default:
    name: jobskillsanalyzer
    external: false
